### ISSUE TITLE
Is there actual need for overflow: hidden in figure's css?

### ISSUE THREAD

**Issue by arggh** [schlosser/pig.js#21]
I noticed that the default styles add `overflow: hidden;` to the `figure` elements' styles.

I tried to understand why it is necessary, but to me it seems like it could be removed with no ill effects?

I even tried to see if anything broke after removing it, and all seems to be working just fine.

Do you have any edge cases or scenarios in mind that might benefit from that css rule?

Also, thanks for building this library!

**Comment by schlosser** [comment]
I included that because I had some problems at small resolutions where some layouts resulted in unfortunate sub-pixel sizing, leading to slight misalignments where the <img> is slightly bigger than the <figure>.

One of those things that could probably be removed in the vast majority of cases but helps out now and then. :)

Just curiosity? Or do you have a use case for removing it?

**Comment by arggh** [comment]
Oh ok, that makes sense. I do have a use case though: I'm including some functionality (a dropdown menu, for example) within the figure elements that might overflow when interacted with. With the `overflow:hidden`-rule in place, the dropdown gets clipped.

**Comment by schlosser** [comment]
I think you could safely remove it for your use case.

Hope that helps!

**Comment by arggh** [comment]
I'll see how it goes. Thanks for the input!
